### ISSUE TITLE
Removed "dead" lines?

### ISSUE THREAD

**Issue by Chris230291** [fairbird/NCam#10]
When the ncam.fs file is loaded and all of the readers are created, the dead readers automatically get removed. When this happens can we have the option to also remove the line from the ncam.fs file please?

Thanks,
Chris

**Comment by fairbird** [comment]
No need to remove line ...
In ncam.conf already this are option you can use it under [global]
> cccam_cfg_reconnect_delay     = 90
cccam_cfg_reconnect_attempts  = 10
 
any line after 10 times not connected as reconnect_attempts set then will be blocked .... and if you want to use it again just restart ncam or your device ....

**Comment by Chris230291** [comment]
Thanks for the reply.
I understand that, but I have a script that scrapes lines from the internet once a day. Eventually there will be thousands of lines in my file, many of which will likely be dead. Trying to connect to dead lines seems pointless and I imagine eventually it will come to the point where it crashes NCam.

**Comment by fairbird** [comment]
This is personal using from your scripts. Then you should be to edit file manually by yourself.
Ncam can not remove or delete the dead lins from hundreds lines.
In this case Ncam will be not work smoothly and fast ...
