### ISSUE TITLE
CCcam.cfg support to Oscam Patch by fairbird

### ISSUE THREAD

**Issue by 420Dope** [fairbird/NCam#13]
Hi,
where can I find your "CCcam.cfg support to Oscam Patch by fairbird" patch? I would to compile it in Oscam myself.
Would be very nice if you can show me where I can find it.

Regards.

**Comment by fairbird** [comment]
Please don't ask about Oscam support here ... Here just for Ncam ..
About CCcam.cfg feature you can follow those commits
https://github.com/fairbird/NCam/commit/0f295cca2041c4645555724d0d0ad5d4cb5db395
https://github.com/fairbird/NCam/commit/00865c744f70ee75d46d57c70e17c24ca056165c
https://github.com/fairbird/NCam/commit/936ee9d8ebacba933b733ccd4e2395de38475163
https://github.com/fairbird/NCam/commit/71ef74b237ff8662c2a01b53c49f3738bbd13bf1
https://github.com/fairbird/NCam/commit/ef8ef1b4416f0f5888bc3560499bcf782116be70
https://github.com/fairbird/NCam/commit/a39443ee8fbd63a38dc697c7849d796883e58449

And Please do not open issue to ask for some commits .. Closed
