### ISSUE TITLE
NCam android-stapi bug in read_sdt

### ISSUE THREAD

**Issue by bevellop** [fairbird/NCam#15]
Hello. I use a NCam android-stapi 13.5

I check all configs from
Ncam-config_ Android-STAPI(BY_samur)-Only_15-10-2022.zip

ncam.conf: 

[dvbapi]
enabled = 1
au = 1
pmt_mode = 5
request_mode = 1
delayer = 60
user = dvbapiau
wi_sosket_id = -1
extended_cw_api = 2
read_sdt=0

ncam.user:

[account]
user                          = dvbapiau
pwd                           = dvbapiau
keepalive                     = 1
au                            = 1
group                         = 1,2,3,4,5,6,7,8,9,10,64

But i need want see provider name I change default settings read_sdt=0 change to 1 or 2 (doesn't matter ). I reboot my receiver. 
Couldn't starting a emu. I go tu pluging manager and see that ncam is stop. Push button start - but no starting a Emu! I need a change change hands in ncam.conf - read_sdt=1 to 0. Reboot receiver. And only after these plugin in starting and work. But i need a config =1.
Thank you!

**Comment by fairbird** [comment]
So ... Do You have  problem or not ?!!
Or Just you give your test result ?!!
Really I cannot understand this open issue ?!!
Please make it more clear ...

**Comment by bevellop** [comment]
Updated my post

**Comment by bevellop** [comment]
If i change change pmt_mode=0,1,2,3,4 i see error il log and couldn't work a emu.
log:
2023-01-26 21:24:07 00000000 s (main) System name = Linux
2023-01-26 21:24:07 00000000 s (main) Host name = localhost
2023-01-26 21:24:07 00000000 s (main) Release = 3.18.24_hi3798mv2x
2023-01-26 21:24:07 00000000 s (main) Version = https://github.com/fairbird/NCam/pull/1 SMP Fri Jun 26 23:23:47 KST 2020
2023-01-26 21:24:07 00000000 s (main) Machine = armv7l
2023-01-26 21:24:07 00000000 s (main) creating pidfile /tmp/.ncam/ncam.pid with pid 3334
2023-01-26 21:24:07 00000000 s (emu) NCam-emu version 798
2023-01-26 21:24:07 00000000 s (config) userdb reloaded: 1 accounts loaded, 0 expired, 0 disabled
2023-01-26 21:24:07 00000000 s (main) signal handling initialized
2023-01-26 21:24:07 00000000 s (config) 2 provid's loaded
2023-01-26 21:24:07 00000000 s (config) 2 service-id's loaded in 0 ms
2023-01-26 21:24:07 00000000 s (reader) Sharing [newcamd] creating thread for device server
2023-01-26 21:24:07 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
2023-01-26 21:24:07 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
2023-01-26 21:24:07 00000000 s (anticasc) anti cascading disabled
2023-01-26 21:24:07 00000000 s (gbox) local gbox failed init
2023-01-26 21:24:07 1B2C2857 p (newcamd) proxy server:13999 newcamd525 (fd=0)
2023-01-26 21:24:07 1B2C2857 p (reader) Sharing [newcamd] proxy initialized, server server:13999
2023-01-26 21:24:07 165CDDD0 c (client) plain dvbapi-client granted (root, au=off)
2023-01-26 21:24:07 165CDDD0 c (dvbapi) dvbapi channelcache loaded from /data/plugin/ncam/ncam.ccache
2023-01-26 21:24:07 165CDDD0 c (dvbstapi) Wi socket id: -1
2023-01-26 21:24:07 6C5EED9B h (webif) webif: decompressed 298097 bytes back into 691712 bytes
2023-01-26 21:24:07 6C5EED9B h (webif) HTTP Server running. ip=0.0.0.0 port=80
2023-01-26 21:24:07 165CDDD0 c (dvbstapi) liboscam_stapi v.1.0.0-user-api initialized
2023-01-26 21:24:07 165CDDD0 c (dvbapi) Detected /dev/stapi/stpti4_ioctl Api: 2, userconfig boxtype: 0 maximum number of filters is 32 (ncam limit is 64)
2023-01-26 21:24:07 165CDDD0 c (dvbapi) ERROR: Can't open device /dev/stapi/stpti4_ioctl (errno=2 No such file or directory)
2023-01-26 21:24:08 1B2C2857 p (reader) server: resolved ip=xxxxxxxxx
2023-01-26 21:24:08 1B2C2857 p (reader) Sharing [newcamd] connecting to server:13999
2023-01-26 21:24:08 1B2C2857 p (newcamd) Newcamd Server: server:13999 - UserID: 208
2023-01-26 21:24:08 1B2C2857 p (newcamd) CAID: 0500 - UA: 0000000000000000 - Provider # 1
2023-01-26 21:24:08 1B2C2857 p (newcamd) Provider ID: 060A00 - SA: 00000000

It's a android-stapi platform feature that we must use a pmt_mode = 5 or bug.

And ERROR: Can't open device /dev/stapi/stpti4_ioctl (errno=2 No such file or directory) - it's ok ?

Thank you

**Comment by rumas84** [comment]
> If i change change pmt_mode=0,1,2,3,4 i see error il log and couldn't work a emu.

it works with: **pmt_mode = 5**


> 2023-01-26 21:24:07 165CDDD0 c (dvbapi) ERROR: Can't open device /dev/stapi/stpti4_ioctl (errno=2 No such file or directory)

if i remember This occurs from Android OS need to be corrected from the Manufacturer Dev team 
but it's not a problem you can ignore it.

which STB you have ? 
can you post the plugin you use ?
thanks
;

**Comment by bevellop** [comment]
Openbox AS4K CI Lite (Android 7)
Ncam [7.0-Nougat-stapi] from sat-universe
https://www.mediafire.com/file/3wplrbrupasqvbr/ncam.arm-android-Amiko-A5_7.0-Nougat-stapi.zip/file

**Comment by rumas84** [comment]
> Openbox AS4K CI Lite (Android 7)

Openbox AS4K  has a weak hardware and a weak software 
compared to other Android-stapi STB's like : ICONE IRON Pro.


> https://www.mediafire.com/file/3wplrbrupasqvbr/ncam.arm-android-Amiko-A5_7.0-Nougat-stapi.zip/file

i need your complete plugin not only NCam binary
thanks,

**Comment by rumas84** [comment]
your plugin looks good ..
can you try this plugin: 
[plugin_su.zip](https://github.com/fairbird/NCam/files/10539533/plugin_su.zip)
httpport: 8888

**Comment by bevellop** [comment]
> your plugin looks good .. can you try this plugin: [plugin_su.zip](https://github.com/fairbird/NCam/files/10539533/plugin_su.zip) httpport: 8888

Thank you. Your settings is work. But when i change read_sdt=0 to 1. Reboot STB. Emulator is shutdown and couldn't starting

**Comment by rumas84** [comment]
> Thank you. Your settings is work. But when i change read_sdt=0 to 1. Reboot STB. Emulator is shutdown and couldn't starting

 stay with read_sdt=0, as i said to you the bug is from your STB weak hardware and weak software.
i have an android-stapi STB (IRON Pro) read_sdt=1 Or read_sdt=2 works normally.

**Comment by fairbird** [comment]
@bevellop 
If you solved your issue as @rumas84 advice. Please close this issue. If not keep it open until we find way to solve it.

**Comment by bevellop** [comment]
rumas84 expressed the point of view that  problem not in emu. That this is a error in firmware STB - openbox. but they have been improving this Android 7 for 5 years. On that there are doubts about this conclusion. And I would like your confirmation of what the problem is: is it an emu or a stb
if this is 100% the culprit of the stb firmware, then I will write to openbox.
Thank you so much!

**Comment by fairbird** [comment]
@bevellop
Please test ncam after this commit and send the log also ..
https://github.com/fairbird/NCam/commit/8c04db6c16a09c22b0f9b3a84846fb0f01412a9b

**Comment by bevellop** [comment]
Thank you so much.  No error

 2023/02/06 19:51:19 00000000 s     (main) System name    = Linux
    2023/02/06 19:51:19 00000000 s     (main) Host name      = localhost
    2023/02/06 19:51:19 00000000 s     (main) Release        = 3.18.24_hi3798mv2x
    2023/02/06 19:51:19 00000000 s     (main) Version        = #1 SMP Fri Jun 26 23:23:47 KST 2020
    2023/02/06 19:51:19 00000000 s     (main) Machine        = armv7l
    2023/02/06 19:51:19 00000000 s     (main) creating pidfile /tmp/.ncam/ncam.pid with pid 3767
    2023/02/06 19:51:19 00000000 s      (emu) Emu version 798
    2023/02/06 19:51:19 00000000 s   (config) userdb reloaded: 1 accounts loaded, 0 expired, 0 disabled
    2023/02/06 19:51:19 00000000 s     (main) signal handling initialized
    2023/02/06 19:51:20 00000000 s   (reader) Sharing [newcamd] creating thread for device server
    2023/02/06 19:51:20 48828F66 p  (newcamd) proxy server:port newcamd525 (fd=0)
    2023/02/06 19:51:20 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
    2023/02/06 19:51:20 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
    2023/02/06 19:51:20 48828F66 p   (reader) Sharing [newcamd] proxy initialized, server server:port
    2023/02/06 19:51:20 5844FEF0 c   (client) plain dvbapi-client granted (dvbapiau, au=off)
    2023/02/06 19:51:20 5844FEF0 c (dvbstapi) Wi socket id: -1
    2023/02/06 19:51:20 0DE32F94 h    (webif) webif: decompressed 232049 bytes back into 499320 bytes
    2023/02/06 19:51:20 0DE32F94 h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
    2023/02/06 19:51:20 5844FEF0 c (dvbstapi) liboscam_stapi v.1.0.0-user-api initialized
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Detected /dev/stapi/stpti4_ioctl Api: 2, userconfig boxtype: 0 maximum number of filters is 32 (ncam limit is 64)
    2023/02/06 19:51:20 48828F66 p   (reader) server: resolved ip=xxxxx
    2023/02/06 19:51:20 48828F66 p   (reader) Sharing [newcamd] connecting to server:port
    2023/02/06 19:51:20 48828F66 p  (newcamd) Newcamd Server: server:port - UserID: 208
    2023/02/06 19:51:20 48828F66 p  (newcamd) CAID: 0500 - UA: 0000000000000000 - Provider # 1
    2023/02/06 19:51:20 48828F66 p  (newcamd) Provider ID: 060A00 - SA: 00000000
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0500 ECM_PID: 1018 PROVID: 040610 
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0500 ECM_PID: 1464 PROVID: 050A00 
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0500 ECM_PID: 1784 PROVID: 060A00 
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0500 ECM_PID: 184C PROVID: 060C00 
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Demuxer 0 found 4 ECM pids and 3 STREAM pids in CA PMT
    2023/02/06 19:51:20 5844FEF0 c   (dvbapi) Demuxer 0 trying to descramble PID 2 CAID 0500 PROVID 060A00 ECMPID 1784 ANY CHID PMTPID 0000 VPID 00DC
    2023/02/06 19:51:21 5844FEF0 c      (ecm) dvbapiau (P: 0500:060A00:071C:1784:0B01: #ECM_L:18E #CW=97A4F0BED2BD239FDDFBEFD8A37EF1E5 HOP:00): found (167 ms) by Sharing
    2023/02/06 19:51:24 5844FEF0 c      (ecm) dvbapiau (P: 0500:060A00:071C:1784:0B01: #ECM_L:18E #CW=075C68713E651ECCDDFBEFD8A37EF1E5 HOP:00): found (567 ms) by Sharing

**Comment by fairbird** [comment]
Does plugin shutdown with change read_sdt to 1 ?!! Or not ?!

**Comment by bevellop** [comment]
Yes. When change read_sdt to 1 plugin shutdown.

**Comment by satxtreme** [comment]
My STB **Openbox AS4K CI PRO PLUS**, i have same problem with **read_sdt = 1**
P.S When I enable this setting and start switching channels, the emulator turns off

**Comment by fairbird** [comment]
@satxtreme 
Where is ncam log ?!!

**Comment by satxtreme** [comment]
> 2023/02/19 14:41:32 54472628 c      (ecm) satxtreme (P: 0500:061200:1644:169E:08DE: #ECM_L:30 #CW=2B5F61EBF060B909C7D51FBB008A6FF9 HOP:01): found (923 ms) by vip2 (F/2/2/2) - Science Europe HD (real 921 ms)
2023/02/19 14:41:42 54472628 c      (ecm) satxtreme (P: 0500:061200:1644:169E:08DE: #ECM_L:30 #CW=8F243EF11623ADE6C7D51FBB008A6FF9 HOP:01): found (438 ms) by vip2 (F/2/2/2) - Science Europe HD (real 435 ms)
2023/02/19 14:41:52 54472628 c      (ecm) satxtreme (P: 0500:061200:1644:169E:08DE: #ECM_L:30 #CW=8F243EF11623ADE64FBE3C49FC750B7C HOP:01): found (395 ms) by vip2 (F/2/2/2) - Science Europe HD (real 392 ms)
2023/02/19 14:42:01 54472628 c   (dvbapi) Demuxer 0 stopped descrambling for program 1644 (Science Europe HD)
2023/02/19 14:42:01 54472628 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0500 ECM_PID: 150E PROVID: 061200 
2023/02/19 14:42:01 54472628 c   (dvbapi) Demuxer 0 found 1 ECM pids and 20 STREAM pids in CA PMT
2023/02/19 14:42:01 54472628 c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 0500 PROVID 061200 ECMPID 150E ANY CHID PMTPID 0000 VPID 14BF
2023/02/19 14:42:02 54472628 c      (ecm) satxtreme (P: 0500:061200:14B4:150E:08DE: #ECM_L:30 #CW=4419E4418EA8E117FDAA7F2626D4E8E2 HOP:01): found (936 ms) by vip2 (F/2/2/2) (real 934 ms)
2023/02/19 14:42:07 54472628 c   (config) 2 service-id's loaded in 0 ms
2023/02/19 14:42:12 54472628 c      (ecm) satxtreme (P: 0500:061200:14B4:150E:08DE: #ECM_L:30 #CW=4419E4418EA8E11740C244463594AF78 HOP:01): found (433 ms) by vip2 (F/2/2/2) - Discovery Central Europe HD (real 433 ms)
2023/02/19 14:42:23 54472628 c      (ecm) satxtreme (P: 0500:061200:14B4:150E:08DE: #ECM_L:30 #CW=ABB19FFB93B2438840C244463594AF78 HOP:01): found (1703 ms) by vip3 (F/2/2/2) - Discovery Central Europe HD (real 1701 ms)
2023/02/19 14:42:33 54472628 c      (ecm) satxtreme (P: 0500:061200:14B4:150E:08DE: #ECM_L:30 #CW=ABB19FFB93B24388D1ADE66439DBE4F8 HOP:01): found (1063 ms) by vip2 (F/2/2/2) - Discovery Central Europe HD (real 1060 ms)
2023/02/19 14:42:40 54472628 c   (dvbapi) Demuxer 0 stopped descrambling for program 14B4 (Discovery Central Europe HD)
2023/02/19 14:42:40 54472628 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0500 ECM_PID: 163A PROVID: 061200 
2023/02/19 14:42:40 54472628 c   (dvbapi) Demuxer 0 found 1 ECM pids and 13 STREAM pids in CA PMT
2023/02/19 14:42:40 54472628 c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 0500 PROVID 061200 ECMPID 163A ANY CHID PMTPID 0000 VPID 15EB
2023/02/19 14:42:40 54472628 c      (ecm) satxtreme (P: 0500:061200:15E0:163A:08DE: #ECM_L:30 #CW=00CD4916BEFFAE6BD1CB22BE1DEBF6FE HOP:01): found (250 ms) by vip2 (F/2/2/2) (real 248 ms)
2023/02/19 14:42:42 54472628 c      (ecm) satxtreme (P: 0500:061200:15E0:163A:08DE: #ECM_L:30 #CW=37BAC4B557120770D1CB22BE1DEBF6FE HOP:01): found (423 ms) by vip2 (F/2/2/2) (real 420 ms)
2023/02/19 14:42:45 54472628 c   (config) 3 service-id's loaded in 0 ms
2023/02/19 14:42:52 54472628 c      (ecm) satxtreme (P: 0500:061200:15E0:163A:08DE: #ECM_L:30 #CW=37BAC4B557120770544242D86A4053FD HOP:01): found (442 ms) by vip2 (F/2/2/2) - Discovery Turbo Xtra HD (real 439 ms)
2023/02/19 14:43:02 54472628 c      (ecm) satxtreme (P: 0500:061200:15E0:163A:08DE: #ECM_L:30 #CW=BBCA38BD450CD425544242D86A4053FD HOP:01): found (474 ms) by vip2 (F/2/2/2) - Discovery Turbo Xtra HD (real 473 ms)
2023/02/19 14:43:06 54472628 c   (dvbapi) Demuxer 0 Unable to open PMT file /tmp/pmt3_1.tmp -> stop descrambling!
2023/02/19 14:43:06 54472628 c   (dvbapi) Demuxer 0 stopped descrambling for program 15E0 (Discovery Turbo Xtra HD)
2023/02/19 14:43:07 54472628 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0500 ECM_PID: 1014 PROVID: 040610 
2023/02/19 14:43:07 54472628 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0500 ECM_PID: 1460 PROVID: 050A00 
2023/02/19 14:43:07 54472628 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0500 ECM_PID: 1780 PROVID: 060A00 
2023/02/19 14:43:07 54472628 c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0500 ECM_PID: 1848 PROVID: 060C00 
2023/02/19 14:43:07 54472628 c   (dvbapi) Demuxer 0 found 4 ECM pids and 3 STREAM pids in CA PMT
2023/02/19 14:43:07 54472628 c   (dvbapi) Demuxer 0 trying to descramble PID 2 CAID 0500 PROVID 060A00 ECMPID 1780 ANY CHID PMTPID 0000 VPID 00D8
2023/02/19 14:43:07 54472628 c      (ecm) satxtreme (P: 0500:060A00:0330:1780:0B01: #ECM_L:1B0 #CW=1BA7FC64C6D0D2E8AF4E5A193A27E47B HOP:01): found (35 ms) by ntv-plus (F/2/2/2) (real 34 ms)

**when switching to a channel with a Russian name, the emulator turns off**
**p.s the most interesting thing is that some Russian-language channels still work, for exemple :**

> 0385:0500@040610@050A00@060A00@060C00|Первый канал HD|TV
0452:0500@050A00@060A00@060C00@040610|Первый канал +2|TV
0386:0500@040610@050A00@060A00@060C00|Россия 1 HD|TV
03F7:0500@040610@050A00@060A00@060C00|Россия 1 +2|TV
0387:0500@040610@050A00@060A00@060C00|НТВ HD|TV
089F:0500@040610@050A00@060A00@060C00|THT HD|TV
0455:0500@040610@050A00@060A00@060C00|Че|TV
0451:0500@040610@050A00@060A00@060C00|СТС|TV
03EC:0500@040610@050A00@060A00@060C00|РЕН ТВ|TV
03F1:0500@040610@050A00@060A00@060C00|ПЯТНИЦА|TV
0529:0500@040610@050A00@060A00@060C00|Суббота!|TV
03EB:0500@040610@050A00@060A00@060C00|Пятый канал|TV
03F5:0500@040610@050A00@060A00@060C00|Звезда|TV
045C:0500@040610@050A00@060A00@060C00|Звезда +2|TV
03F8:0500@040610@050A00@060A00@060C00|ЗВЕЗДА Плюс|TV
044E:0500@040610@050A00@060A00@060C00|Домашний|TV
0456:0500@040610@050A00@060A00@060C00|ТВЦ|TV
0525:0500@040610@050A00@060A00@060C00|РБК-ТВ|TV
0453:0500@040610@050A00@060A00@060C00|ОТР|TV
