### ISSUE TITLE
Reload ncam.fs

### ISSUE THREAD

**Issue by Chris230291** [fairbird/NCam#17]
Can we have an option to reload ncam.fs every n hours please?
This would save having to reload all readers and do it externally with scripts.

**Comment by fairbird** [comment]
From Ncam.config (cccam_cfg_reconnect_delay)
or From webinterface
![Selection_001](https://user-images.githubusercontent.com/1761779/223978021-95fbde78-32b0-4af3-82c9-54fe5faa276b.png)
![Selection_002](https://user-images.githubusercontent.com/1761779/223978027-f3abbad1-608f-4978-a1a6-2997f16692dd.png)

**Comment by Chris230291** [comment]
Isn't this just initial connection? After the line fails it gets removed by ncam.
I am talking about trial urls. At some point the trial line expires and a new line must be fetched.

**Comment by fairbird** [comment]
No way .... Should be to restart ncam bin files to get new free servers not just to reload config file such as CCcam.cfg or  ncam.fs .
Ncam need restart to make refresh and then get new url site.
Also you can not get more than one free trial line each 24h or 48h ..

**Comment by Chris230291** [comment]
OK no problem.
