### ISSUE TITLE
Treat resolve errors as connection fails

### ISSUE THREAD

**Issue by Chris230291** [fairbird/NCam#18]
Dead / broken lines get removed after x attempts. But if this happens `can't resolve xxxxxxxxxx, error: Name does not resolve` the server does not get removed, but I think it should.

**Comment by fairbird** [comment]
That is normally ... If url server does not work you will be get (error: Name does not resolve) .. So that issue from free server site not from ncam ..

**Comment by Chris230291** [comment]
Yes it is issue with server I understand that. What I would like is for NCAM to treat it like other connection failures and remove the line.

![image](https://user-images.githubusercontent.com/5328818/224190580-55ec6951-84ae-42a9-8a69-1e4fbc4124f7.png)

After 2 attempts it should be removed.

**Comment by Chris230291** [comment]
I am not sure if this is the correct place and I don't know C. 
Maybe this help you understand?

![image](https://user-images.githubusercontent.com/5328818/224193102-330b82c6-8a65-4ab4-89e0-d1b56c4340d4.png)

**Comment by fairbird** [comment]
It is not easy to solve those issues ...
More and more things cause that error .. 
-site down
-url does not work
-new protection on free servers site
-Some internet issues
- etc .....

So It is hard to figure out and solve all those .. But I will try to do some things for test in new version .. as soon as possible

**Comment by fairbird** [comment]
Just small fixes (Please have try)
https://github.com/fairbird/NCam/commit/7db6535f190bec50fe1fb887869963a18edca2a3

**Comment by Chris230291** [comment]
Thank you it appears to be working.

**Comment by Chris230291** [comment]
It might be working too good and not giving servers a chance to connect.
Does it remove readers on first network error or does it still use the `cccam reader reconnect attempt` value?
I seem to be getting less working readers after updating.

**Comment by fairbird** [comment]
{ block_connect(rdr); } = Will be Block the dead server with wrong url or other issues ... So like that you got less working readers !!
