### ISSUE TITLE
Please fix Buffer Patch v3 vu+ Reciever 

### ISSUE THREAD

**Issue by Yoshi1981** [fairbird/NCam#25]
Please fix Buffer Patch v3 vu+ Reciever 
[buffer.v3.patch.txt](https://github.com/fairbird/NCam/files/14280214/buffer.v3.patch.txt)

**Comment by fairbird** [comment]
Ncam have different (ffdecsa) code then Oscam .. So Ncam different then oscam for about buffing ..
But I will look on the patch ...

**Comment by fairbird** [comment]
@Yoshi1981 

if the server provider returns the CWs to us on time, then everything is fine, and there is no need for us to buffer separately and load our device unnecessarily,
and therefore the server provider solves these delays on its own server...
on the other hand, this buffer patch is buggy and crashes on other devices
I tested this patch a while ago and it doesn't work for me on my device, it crashes after the first ecm,
and I consider this patch unnecessary and bad.

**Comment by Yoshi1981** [comment]
OK thanks yes ncam fairboard and oscam smod schimmel the best way ! 

Or Neutrino or bpanther With ncam Work all without icam Patches thanks for Bpanther and vanhofen

All normal in the Neutrino Images 

Cool 😃
