### ISSUE TITLE
Module Stream Relay

### ISSUE THREAD

**Issue by WXbet** [fairbird/NCam#26]
Hi @fairbird,
I think the new Stream Relay Module in oscam trunk could be interesting for your project here. It reduces CPU load on older Receiver (400 MHz class) between 10-20%. It is possible to send you the original patch without the cak7 stuff. If you have any questions, feel free to contact me.
Regards @WXbet

**Comment by fairbird** [comment]
Already I have that cods but with some things different .. But sure .. Please send the patch I will be study it.
Thank you

**Comment by WXbet** [comment]
Here are the changes that brings MODULE_STREAM relay based on libdvbcsa into oscam trunk: 
[001-streamrelay-libdvbcsa-11734-11739.patch](https://github.com/fairbird/NCam/files/14513708/001-streamrelay-libdvbcsa-11734-11739.patch)

**Comment by fairbird** [comment]
Is the patch same (fegol) patch here ?! With some edit from your side ?!!
https://board.streamboard.tv/forum/thread/48323-streamrelay-patch-laber-thread/?postID=613977#post613977

**Comment by WXbet** [comment]
Absolutly yes, with some changes. My patch is the oscam trunk version with relay buffer setting and some Makefile, CMakeList.txt changes. You need, like oscam-emu, power-vu stream relay changes to get it working with libdvbcsa and get rid of ffdecsa.

**Comment by fairbird** [comment]
Done !
https://github.com/fairbird/NCam/commit/20aff06304a4d41e86c05b47098324a916b14c45
