### ISSUE TITLE
ncam crashes when using wrong libdvbcsa shared library

### ISSUE THREAD

**Issue by WXbet** [fairbird/NCam#29]
You need to implement something like this to prevent crashing and show infos about wrong libdvbcsa in startlog:
```
#include <dlfcn.h>

int32_t* has_dvbcsa_ecm = 0;
has_dvbcsa_ecm = dlsym(RTLD_DEFAULT, "dvbcsa_bs_key_set_ecm");

cs_log("INFO: %s dvbcsa parallel mode = %d (relay buffer time: %d ms)", (!has_dvbcsa_ecm) ? "(wrong)" : "(ecm)" , cluster_size, cfg.stream_relay_buffer_time);

if (has_dvbcsa_ecm)
{
dvbcsa_bs_key_set(...);
}
```

**Comment by WXbet** [comment]
Still in investigation...

**Comment by WXbet** [comment]
Look at this commit to avoid crashes when using wrong libdvbcsa:
https://github.com/oscam-emu/oscam-patched/commit/56f95b9d2b8d0341d8a2d329cd9178652f9a18f5

**Comment by fairbird** [comment]
Have you test it with ncam ?!! If you tested and work fine then push PR please !

**Comment by WXbet** [comment]
This should work fine: https://github.com/fairbird/NCam/pull/30
I've seen so many OpenSSL 3 build warnings. Maybe you can pick some changes regarding openssl from oscam-tunk to silence this.

**Comment by fairbird** [comment]
I have apply the commit
https://github.com/fairbird/NCam/commit/3874cfd5b72a5d7c26812fcd29992c2a8fb7e9fc
And For OpenSSL 3, there is no need to fix it because I think it's good for now and there are no warnings
https://github.com/fairbird/NCam/actions/runs/8373227716/job/22925867225
