### ISSUE TITLE
Memory usage after 24 days

### ISSUE THREAD

**Issue by MegaV0lt** [fairbird/NCam#41]
I noticed that memory usage gets high after a few days. What can be the cause?

![Auswahl_112](https://github.com/user-attachments/assets/6a3d5107-92d9-4e9d-abdf-53b0dbc80fc6)

**Comment by fairbird** [comment]
I do not know really from where exactly !! You need to look on the log.

And My friend this is not issue form source to build ncam .. These matters cannot be discussed here.. they should be discussed in the forums only...
