### ISSUE TITLE
CCCam.cfg

### ISSUE THREAD

**Issue by be18** [fairbird/NCam#42]
Hello,

Is possible to change or configure the settings that ncam will use for lines on cccam.cfg?
Like is use group = 64 fallback =1
is possible to use the setthings we want?

**Comment by fairbird** [comment]
Add new option for what you asked !
You can build new Ncam and test it or wait to me to built next version of Ncam.

![2024-11-06 11-46-24](https://github.com/user-attachments/assets/c771e6e1-a42d-4ea8-bd76-4b5cf6b64732)
or you can add the option 'cccam_cfg_fallback = 0' in (ncam.config) under [global] leble

**Comment by be18** [comment]
Thank you, but maybe i dont explain well... i would like to set others settings availabe on the readers page... Like caid, ident...

tks

**Comment by fairbird** [comment]
That What I have done .. New option was add it . In latest ncam version you can not find it. Just now if you build new file you will find new option. But not in readers page (Ncam.server) file you can add it in (ncam.config) file under [global] leble as "cccam_cfg_fallback = 0" or from web under (CONFIGURATION > Global > CCcam.cfg/ncam.fs)

**Comment by be18** [comment]
How do i choose the caid = , i think that you only add the option for fallback. But i want to add the caid = for example.
Thank you

**Comment by fairbird** [comment]
You can control caids through the ncam.server file.
