### ISSUE TITLE
Default ncam.conf example file causes ncam service to stop on editing config.

### ISSUE THREAD

**Issue by sgmihai** [fairbird/NCam#43]
I am using ncam-git package from AUR on archlinux (https://aur.archlinux.org/packages/ncam-git).
It copies the example config file (Distribution/doc/example/ncam.conf) to /etc/ncam on install (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ncam-git#n54)
I noticed that modifying any setting in the webui after this fresh install causes the ncam service to stop.
Through trial and error, I have found this part of the .conf to be responsable for the crash:
> [cs378x]
> port          = 30000@0100:FFFFFF;30001@0200:FFF000,FFFF00;30002@0300:FFFFFF

I do not know the cause for it or what that line is supposed to do, but maybe it should get fixed so the example config provided does not cause improper functioning of ncam ? Maybe comment out those lines, or edit them, I've no idea what they do :)
Thanks.

**Comment by fairbird** [comment]
Sorry .. I did not using or supporting (AUR on archlinux) ...
Only E2 devices and linux/windows system operations.

**Comment by fairbird** [comment]
You can ask Who supported archlinux. From my side I can not (Never using before)

> https://bbs.archlinux.org/

>Maintainer: lod <aur@cyber-anlage.de>
Contributer: Christopher Reimer <mail+vdr4arch[at]c-reimer[dot]de>
Contributer: Julian Xhokaxhiu <info@julianxhokaxhiu.com>

**Comment by sgmihai** [comment]
Maybe I didn't make myself clear enough. This is not related to archlinux specifically. Archlinux is simply Linux. Btw it seems to be the only linux distribution with an ncam package: https://repology.org/project/ncam/versions

The problem resides in just one .conf entry from your examples, that I pointed above, with the cs378x. It is arguable that the package should or should not use that .conf file as starting point when installing it, but I think the .conf file provided should be valid on a clean install.
I see it is 5 years old already.
Can you maybe check on your system, with a clean ncam install, using just that .conf file from examples, and trying to modify a setting from the webui (like number of lines to log, from 256 to 200), if this results in a service stop/crash ?
I could maybe test it on some other systems, but I am sure the result will be the same. Maybe in 5 years something in that particular config entry became a bit invalid and causing the crash, when attempting to read and rewrite it as .conf.
I would fix it myself but I am a noob, I just got dvbapi working with tvheadend, after trying for 2 hours :)

Edit: Looks like it's the same example .conf file from oscam https://git.streamboard.tv/common/oscam/-/blob/master/Distribution/doc/example/oscam.conf?ref_type=heads
I will try and see if I get the same behaviour from oscam -git

**Comment by fairbird** [comment]
On E2 devices and Linux/windows system operations  (No problem ,, No crashing)
Here latest config files you can test it for E2 but you can use it for Linux with change some lines to make it compatible with your system.
https://www.mediafire.com/file/tub0d1wj472cvs3/Ncam-config-OE2.0_23-10-2024.zip/file
And I have updated Documents also ...
https://github.com/fairbird/NCam/commit/9def2639aa3af68a39e5c2f3f1d1637301b68534

**Comment by sgmihai** [comment]
The new default config does not cause crash anymore, changing to port  = 13001@ probably fixed it.
Thanks
