### ISSUE TITLE
Try to read from inet before bindwait is over

### ISSUE THREAD

**Issue by MegaV0lt** [fairbird/NCam#9]
````
2022/08/16 15:03:11 00000000 s    (files) libcurl: (6) Could not resolve host: ###
2022/08/16 15:03:11 00000000 s        (-) -- Skipped 2 duplicated log lines --
2022/08/16 15:03:11 00000000 s    (files) libcurl: (6) Could not resolve host: ###
2022/08/16 15:03:11 00000000 s   (config) ncam.fs read lines: C:0 N:0 L:0 R:0
````

After systemrestart and ncamstart the ncam does not respect the setting "BindWait" so it can not acceess the web...

Edit: I think ncam should ait for webaccess at least the bindwait time or a fixed time or until it detects that the network is up.
Also it should retry afte a certain amount of time iw inet access fails

**Comment by fairbird** [comment]
No problem here with me ... 
Maybe you have some issues in your software what you are using ...

**Comment by MegaV0lt** [comment]
I use Debian 11.4
I changed the systemd service so the oscam only starts after network-online
